export const AUTHENTICATE_PATIENT = 'AUTHENTICATE_PATIENT'
export const AUTHENTICATE_DOCTOR = 'AUTHENTICATE_DOCTOR'
export const UNAUTHENTICATE_PATIENT = 'UNAUTHENTICATE_PATIENT'
export const UNAUTHENTICATE_DOCTOR = 'UNAUTHENTICATE_DOCTOR'

export const PUT_PATIENT_IN_SESSION = 'PUT_PATIENT_IN_SESSION'
export const FETCH_PATIENT_APPOINTMENTS = 'FETCH_PATIENT_APPOINTMENTS' 

export const START_DOCTOR_SESSION = 'START_DOCTOR_SESSION'
export const END_DOCTOR_SESSION = 'END_DOCTOR_SESSION'

export const SET_USER_DOCTOR = 'SET_USER_DOCTOR'

export const FETCH_DOCTOR_APPOINTMENTS_TODAY = 'FETCH_DOCTOR_APPOINTMENTS_TODAY'
export const FETCH_DOCTOR_SESSIONS = 'FETCH_DOCTOR_SESSIONS'

export const CLINIC_NEXT_PATIENT = 'CLINIC_NEXT_PATIENT'